name: CI + CD - Pipeline Completo

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: Executar CI (Testes)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          pip install pylint
          pylint $(git ls-files '*.py')

  cd:
    name: Executar CD (Build)
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          mkdir -p build_output
          zip -r build_output/project.zip . -x "*.git*" "*.github*" "__pycache__/*" "*.venv/*" "venv/*" "*.pytest_cache/*"
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build_output/project.zip
      - run: echo "✅ Projeto zipado e pronto para próxima etapa."
