name: Notificação de Pull Request

on:
    pull_request:
        branches: [main]

jobs:
    discord:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Discord Webhook Action
              uses: tsickert/discord-webhook@v7.0.0
              with:
                  webhook-url: ${{ secrets.PR_WEBHOOK }}
                  raw-data: notify_pr.json